# Generated by Django 5.2.5 on 2025-08-30 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=10, unique=True)),
                ('quantity', models.IntegerField(default=0)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pouch_In',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('pouch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pouch', verbose_name='pouch')),
            ],
        ),
        migrations.CreateModel(
            name='Pouch_Out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('getter', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('purpose', models.CharField(max_length=100)),
                ('status', models.CharField(default='Free', max_length=100)),
                ('given', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('pouch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pouch', verbose_name='')),
            ],
        ),
    ]
