# Generated by Django 5.2.5 on 2025-08-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pouch_out',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
