# Generated by Django 5.2.5 on 2025-08-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pouch',
            name='inbounded_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
