# Generated by Django 5.2.5 on 2025-09-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_pouch_out_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pouch_out',
            name='date_created',
            field=models.DateField(),
        ),
    ]
