# Generated by Django 5.2.5 on 2025-08-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_pouch_quantity_alter_pouch_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pouch_out',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
