# Generated by Django 5.2.5 on 2025-08-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_pouch_out_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pouch_out',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
